const ArticleActionTypes = {
  FETCHING_ARTICLES: 'FETCHING_ARTICLES',
  FETCH_ARTICLES_SUCCESS: 'FETCH_ARTICLES_SUCCESS',
  FETCH_ARTICLES_ERROR: 'FETCH_ARTICLES_ERROR',
  CREATE_ARTICLE_SUCCESS: 'CREATE_ARTICLE_SUCCESS',
  CREATE_ARTICLE_ERROR: 'CREATE_ARTICLE_ERROR',
  EDIT_ARTICLE_SUCCESS: 'EDIT_ARTICLE_SUCCESS',
  EDIT_ARTICLE_ERROR: 'EDIT_ARTICLE_ERROR',
  DELETE_ARTICLE_SUCCESS: 'DELETE_ARTICLE_SUCCESS',
  DELETE_ARTICLE_ERROR: 'DELETE_ARTICLE_ERROR',
}

export default ArticleActionTypes