const BlogActionTypes = {
  FETCHING_BLOG_POSTS: 'FETCHING_BLOG_POSTS',
  FETCH_BLOG_POSTS_SUCCESS: 'FETCH_BLOG_POSTS_SUCCESS',
  FETCH_BLOG_POSTS_ERROR: 'FETCH_BLOG_POSTS_ERROR',
  CREATE_BLOG_POST_SUCCESS: 'CREATE_BLOG_POST_SUCCESS',
  CREATE_BLOG_POST_ERROR: 'CREATE_BLOG_POST_ERROR',
  EDIT_BLOG_POST_SUCCESS: 'EDIT_BLOG_POST_SUCCESS',
  EDIT_BLOG_POST_ERROR: 'EDIT_BLOG_POST_ERROR',
  DELETE_BLOG_POST_SUCCESS: 'DELETE_BLOG_POST_SUCCESS',
  DELETE_BLOG_POST_ERROR: 'DELETE_BLOG_POST_ERROR',
}

export default BlogActionTypes